apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: my-ns
spec:
  containers:
  - name: busy
    image: 
        radial/busyboxplus        
    command:
      - sleep
      - "3600"
    env:
    - configMapRef:
        name: my-config
