apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myapp.ingress.com
    http:
      paths:
      - path: /nginx
		pathType: Exact
        backend:
          service:
            name: nginx
            port:
              number: 80