apiVersion: v1
kind: Pod
metadata:
  name: myredis
  namespace: default
spec:
  containers:
  - name: busy
    image: 
        redis    
    command:
      - sleep
      - "3600"
    envFrom:
    - secretRef:
        name: my-new-secret
